### ISSUE TITLE
Switch the default git branch from master to main

### ISSUE THREAD

**Issue by oliverklee** [T-Regx/CrossDataProviders#12]
The term "master" is associated with racism. So many open source projects are switching their default branch to something else (most often to "main"). Here's how to do it: https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

**Comment by Danon** [comment]
We all agree that racism is one of the most regrettable belief, but I think breaking the version control conventions because of certain opinions is a step too far. In my conclusion, what is or isn't associated with variants of hate is subjective. I don't find this as a good enough reason to step away from the VCS conventions.

Remember that you can checkout your local branches with whatever name you prefer:

```sh
git checkout -b main origin/master
```

Sorry and thank you for your Issue.
